#!/bin/sh 

REFERENCE_SERVER=srv003

# script and binaries shares
mount -t nfs $REFERENCE_SERVER:bin /usr/local/bin
mount -t nfs $REFERENCE_SERVER:sbin /usr/local/sbin

# Debian OS reference shares - current build
mount -t nfs -r $REFERENCE_SERVER:debian1 /mnt/debian1
mount -t nfs -r $REFERENCE_SERVER:debian2 /mnt/debian2

# CPAN mount
mount -t nfs -r $REFERENCE_SERVER:cpan /mnt/cpan
